// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCljSXrrTqXN-eYBaZ-Cr_HJfgBn1R8c',
    appId: '1:469487414723:web:fead013e4605f350d82176',
    messagingSenderId: '469487414723',
    projectId: 'physioup-958f0',
    authDomain: 'physioup-958f0.firebaseapp.com',
    storageBucket: 'physioup-958f0.firebasestorage.app',
    measurementId: 'G-WJ6PCRN934',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi8NaLatQBMnfW9fQ3Y7twN-olojkE4yQ',
    appId: '1:469487414723:android:19c9ad85f1295f9dd82176',
    messagingSenderId: '469487414723',
    projectId: 'physioup-958f0',
    storageBucket: 'physioup-958f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgJYUwlax2YnzfiK5ym5XaS4dIAMowng',
    appId: '1:469487414723:ios:c219a63fb5477615d82176',
    messagingSenderId: '469487414723',
    projectId: 'physioup-958f0',
    storageBucket: 'physioup-958f0.firebasestorage.app',
    iosBundleId: 'com.shawketibrahim.physioup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrgJYUwlax2YnzfiK5ym5XaS4dIAMowng',
    appId: '1:469487414723:ios:b38aaa495dbccd8ed82176',
    messagingSenderId: '469487414723',
    projectId: 'physioup-958f0',
    storageBucket: 'physioup-958f0.firebasestorage.app',
    iosBundleId: 'com.example.phsyioUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYCljSXrrTqXN-eYBaZ-Cr_HJfgBn1R8c',
    appId: '1:469487414723:web:f192f14b224830d9d82176',
    messagingSenderId: '469487414723',
    projectId: 'physioup-958f0',
    authDomain: 'physioup-958f0.firebaseapp.com',
    storageBucket: 'physioup-958f0.firebasestorage.app',
    measurementId: 'G-LXNQFEHBQJ',
  );
}
