name: Build Windows

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
        with:
          flutter-version: 3.27.3
      - run: flutter config --enable-windows-desktop
      - run: flutter create .
      - run: flutter build windows
      - name: Build APK
        run: flutter build apk --release
      - uses: actions/upload-artifact@master
        with:
          name: windows
          path: |
            build\windows
            build\app
      